name: Deploy Frontend to Azure

on:
  push:
    branches: [main]

env:
  REGISTRY_NAME: homemanagerregistry.azurecr.io
  IMAGE_NAME: homemanager-frontend
  IMAGE_TAG: latest
  RESOURCE_GROUP: home-manager-rg
  WEBAPP_NAME: home-manager-front

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_LINUX }}

      - name: Login to ACR
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY_NAME }} \
            --username "${{ secrets.REGISTRY_USERNAME }}" \
            --password-stdin

      - name: Install Node dependencies and build Angular
        run: |
          cd home-manager-project
          npm install
          npm run build -- --configuration production

      - name: Build and Push Frontend Image
        run: |
          docker build --no-cache -t ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ./home-manager-project
          docker push ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name ${{ env.WEBAPP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
