name: Deploy to Azure Linux App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Встановлення залежностей фронтенду
      - name: Install frontend dependencies
        working-directory: ./home-manager-project
        run: npm install

      # Збірка Angular до папки backend'у
      - name: Build Angular app
        working-directory: ./home-manager-project
        run: npm run build -- --configuration production --output-path=../home-manager-api/dist

      # Встановлення залежностей бекенду (включаючи @azure/storage-blob)
      - name: Install backend dependencies
        working-directory: ./home-manager-api
        run: npm install

      # Перевірка наявності index.html
      - name: Check dist/index.html
        run: |
          ls -lh ./home-manager-api/dist
          cat ./home-manager-api/dist/index.html || echo "index.html not found"

      # Архівування разом з node_modules
      - name: Create deployable ZIP (WITH node_modules)
        working-directory: ./home-manager-api
        run: zip -r ../app.zip .

      - name: Check ZIP contents
        run: unzip -l app.zip | grep index.html || echo "index.html not in zip"

      # Вхід до Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_LINUX }}

      # Розгортання ZIP на Linux Web App
      - name: Deploy to Azure App Service
        run: |
          az webapp deploy \
            --resource-group home-manager-rg \
            --name home-manager-app-linux \
            --src-path app.zip \
            --type zip
